version: '3'
services:
  azure-vote-back:
    image: nginx:latest
    container_name: azure-vote-back
    environment:
      ALLOW_EMPTY_PASSWORD: "No"
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: nginx:latest
    container_name: azure-vote-front
    environment:
      REDIS: azure-vote-back
    ports:
        - "8080:80"
